### PR TITLE
Add DataView

### PR DESCRIPTION
**Pull request by jackkoenig**
Introducing `DataView` 🙂 

The documentation is complete. Here are the outputs of mdoc:
* [Explanation](https://gist.github.com/jackkoenig/d8241e7ce370234738de27ef552008d7)
* [Cookbook](https://gist.github.com/jackkoenig/6e8d8c92012e0992f0c7bb1093c0bcce)

This is a large addition, but keep in mind that 1590 lines of change are documentation and tests (~70%)

### TODO
- [x] MDoc
- [x] Finish ScalaDoc
- [x] Fill in link to docs for error messages
- [x] Implement nested views (see the "ignore" test)
- [x] Provide `DataProduct.contains` 
- [x] Implement `PartialDataView`
- [x] Implement `.toTarget` on views
- [x] Change to `.viewAs[T]` instead of `.viewAs(new T)`
- [x] Support naming, eg. `val foo = (new MyHW).viewAs(new OtherType)`, currently the hardware gets a temporary name
- [x] Handle differing widths

### Follow on PR work
- [ ] Handle dynamic indexing of Vec views (currently left as an error)
- [ ] Built-in `DataViews` like `HWTuple`
- [ ] Implement `FlatIO` with `DataView`
- [ ] Automatically derive `andThen` `DataViews`. This works in Scala 2.13 but leads to diverging implicit expansion in 2.12 (because of identityView)
- [ ] Implement `.readOnlyView` using views
- [ ] Maybe change to `DataProduct.lookup` (to get a `String` name for fields that may have a bug)
- [ ] Subword stuff (eg. being able to view an `Aggregate` as a `UInt` or vice versa)
- [ ] Subword assignment (make .apply on Bits return views, then we could assign to them)
- [ ] Support for literals (should go along with support in `.asTypeOf`)
- [ ] Handle default values, what if a field of a Target is a literal for a particular instance?

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

 - documentation  
 - code refactoring  
  - new feature/API 

#### API Impact

Important API Expansion (not necessarily "large" since it is focused, but it is a pretty big feature)

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

 - Squash

#### Release Notes

DataView is a mechanism for "viewing" Scala objects as a subtype of
`Data`. Often, this is useful for viewing one subtype of `Data`, as
another. One can think about a DataView as a cross between a
customizable cast and an untagged union.

A DataView has a Target type `T`, and a View type `V`. DataView requires
that an implementation of `DataProduct` is available for Target types.
DataProduct is a type class that provides a way to iterate on `Data`
children of objects of implementing types.

If a DataView is provided for a type T to a type V, then the function
.viewAs[V] (of type T => V) is available. The object (of type T) returned
by .viewAs is called a "View" and can be used as both an rvalue and an
lvalue. Unlike when using an .asTypeOf cast, connecting to a "View" will
connect to the associated field or fields of the underlying Target.

DataView also enables .viewAsSupertype which is available for viewing
Bundles as a parent Bundle type. It is similar to .viewAs but requires
a prototype object of the Target type which will be cloned in order to
create the returned View. .viewAsSupertype maps between the
corresponding fields of the parent and child Bundle types.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.x, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by edwardcwang** [comment]
No PR description or Scaladocs?

**Comment by jackkoenig** [comment]
> No PR description or Scaladocs?

The majority of public APIs (but not all) have ScalaDoc, and description is coming. This is a draft PR for a reason 🙂

**Comment by jackkoenig** [comment]
After discussion with @azidar, we need to add a `DataProduct.contains`. The `dataIterator` API is important for total `DataViews`, but would be very slow for merely checking things in `PartialDataViews` where the target type is a module. For most `DataProducts` (and perhaps by default)`, `.contains` is easily implementable from `dataIterator`. For `DataProduct[BaseModule]`, we can implement `.contains` cleverly by seeing if the `.id` for the argument is greater than the id of the Module itself and less than whatever the final id is in the module (this could be set at the end of the `Module.apply` wrapper).

**Comment by jackkoenig** [comment]
For anyone following along at home, this is nearing completion and I have "published" the initial version of the docs (see the links in the original PR comment).

**Comment by kammoh** [comment]
This is very smart solution to what I believe to be a problem during integration Chisel-based components.
Great job @jackkoenig!

**Comment by jackkoenig** [comment]
Note that the API has changed a little bit, I have updated the docs with the changes.

**Comment by jackkoenig** [comment]
This is done and ready for merging. There are some follow on things to enhance this and I'm sure there are bugs but it'd be nice to get this on `3.5-SNAPSHOT` so people can try it out!

File: core/src/main/scala/chisel3/Data.scala [hunk 1]
```diff
@@ -488,6 +547,14 @@ abstract class Data extends HasId with NamedComponent with SourceInfoDoc {
     }
     requireIsHardware(this)
     topBindingOpt match {
+      // DataView
+      case Some(ViewBinding(target)) => reify(target).ref
+      case Some(AggregateViewBinding(viewMap, _)) =>
+        viewMap.get(this) match {
+          case None => materializeWire() // FIXME FIRRTL doesn't have Aggregate Init expressions
```
Comment (azidar) [inline core/src/main/scala/chisel3/Data.scala:554]: Is this something to be fixed in a future PR?

File: core/src/main/scala/chisel3/Module.scala [hunk 2]
```diff
@@ -195,7 +195,7 @@ package internal {
         _component = _proto._component
         None
       }
-      // This module doesn't acutally exist in the FIRRTL so no initialization to do
+      // This module doesn't actually exist in the FIRRTL so no initialization to do
```
Comment (azidar) [inline core/src/main/scala/chisel3/Module.scala:198]:
```suggestion
      // This module doesn't ackshually exist in the FIRRTL so no initialization to do
```

File: core/src/main/scala/chisel3/Module.scala [hunk 3]
```diff
@@ -399,7 +394,9 @@ package experimental {
     final def toAbsoluteTarget: IsModule = {
       _parent match {
         case Some(parent) => parent.toAbsoluteTarget.instOf(this.instanceName, toTarget.module)
-        case None => toTarget
+        case None =>
+          // FIXME Special handling for Views - evidence of weirdness of .toAbsoluteTarget
```
Comment (azidar) [inline core/src/main/scala/chisel3/Module.scala:398]: Maybe more of a comment for why this is necessary?

File: core/src/main/scala/chisel3/RawModule.scala [hunk 4]
```diff
@@ -157,6 +158,9 @@ trait RequireSyncReset extends Module {
 
 package object internal {
 
+  /** Marker trait for modules that are not true modules */
+  private[chisel3] trait PseudoModule extends BaseModule
```
Comment (azidar) [inline core/src/main/scala/chisel3/RawModule.scala:162]: I like this. I approve.

File: core/src/main/scala/chisel3/RawModule.scala [hunk 5]
```diff
@@ -264,4 +268,28 @@ package object internal {
       }
     }
   }
+
+  /** Internal API for [[ViewParent]] */
+  sealed private[chisel3] abstract class ViewParentAPI extends RawModule()(ExplicitCompileOptions.Strict) {
```
Comment (azidar) [inline core/src/main/scala/chisel3/RawModule.scala:273]: Why does this not extend `PseudoModule` ? I see you mix it in later?

File: core/src/main/scala/chisel3/RawModule.scala [hunk 6]
```diff
@@ -264,4 +268,28 @@ package object internal {
...
+    private[chisel3] def fakeComponent: Component
+    private[chisel3] def absoluteTarget: IsModule = ModuleTarget(this.circuitName, "_$$AbsoluteView$$_")
```
Comment (azidar) [inline core/src/main/scala/chisel3/RawModule.scala:275]: Why did you have to implement `absoluteTarget` but not `toTarget`?

File: core/src/main/scala/chisel3/RawModule.scala [hunk 7]
```diff
@@ -264,4 +268,28 @@ package object internal {
...
+    * @note this is a val instead of an object because of the need to wrap in Module(...)
+    */
+  private[chisel3] val ViewParent = Module.do_apply(new ViewParentAPI with PseudoModule {
+    // This module is not instantiable
+    override private[chisel3] def generateComponent(): Option[Component] = None
+    override private[chisel3] def initializeInParent(parentCompileOptions: CompileOptions): Unit = ()
+    // This module is not really part of the circuit
+    _parent = None
+
+    // Sigil to mark views, starts with '_' to make it a legal FIRRTL target
```
Comment (azidar) [inline core/src/main/scala/chisel3/RawModule.scala:289]: Nice use of the word `Sigil`

File: core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+  /** Returns a checker to test if the containing object contains a `Data` object
+    * @note Implementers may want to override if iterating on all `Data` is expensive for `A` and `A`
+    *       will primarily be used in `PartialDataViews`
+    * @note The returned value is a function, not a true Set, but is describing the functionality of
+    *       Set containment
+    * @param a Containing object
+    * @return A checker that itself returns True if a given `Data` is contained in `a`
+    *         as determined by an `==` test
+    */
+  def dataSet(a: A): Data => Boolean = dataIterator(a, "").map(_._1).toSet
```
Comment (azidar) [inline core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala:41]: Woah. This took me a minute to grok. Because the set's apply method is whether it contains it, a Set is actually a `Data => Boolean` ?

File: core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+      }
+    }
+    // Overridden for performance
+    override def dataSet(a: BaseModule): Data => Boolean = {
+      val lastId = a._lastId // Not cheap to compute
+      // Return a function
+      e => e._id > a._id && e._id <= lastId
+    }
+  }
+}
```
Comment (azidar) [inline core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala:72]: newline

File: core/src/main/scala/chisel3/experimental/dataview/DataView.scala [hunk 10]
```diff
@@ -0,0 +1,148 @@
...
+  implicit private[chisel3] val sourceInfo: SourceInfo
+) {
+  /** Indicates if the mapping contains every field of the target */
+  def total: Boolean = _total
+
+  override def toString: String = {
+    val base = sourceInfo.makeMessage(x => x)
+    val loc = if (base.nonEmpty) base else "@unknown"
+    val name = if (total) "DataView" else "PartialDataView"
+    s"$name(defined $loc)"
```
Comment (azidar) [inline core/src/main/scala/chisel3/experimental/dataview/DataView.scala:60]: NICE

File: core/src/main/scala/chisel3/experimental/dataview/DataView.scala [hunk 11]
```diff
@@ -0,0 +1,148 @@
...
+  }
+
+  /** Compose two `DataViews` together to construct a view from the target of this `DataView` to the
+    * view type of the second `DataView`
+    *
+    * @param g a DataView from `V` to new view-type `V2`
+    * @tparam V2 View type of `DataView` `g`
+    * @return a new `DataView` from the original `T` to new view-type `V2`
+    */
+  def andThen[V2 <: Data](g: DataView[V, V2])(implicit sourceInfo: SourceInfo): DataView[T, V2] = {
```
Comment (azidar) [inline core/src/main/scala/chisel3/experimental/dataview/DataView.scala:70]: I suppose this is something the user has to do; we can't rely on the compiler to infer this for us?

File: core/src/main/scala/chisel3/experimental/dataview/package.scala [hunk 12]
```diff
@@ -0,0 +1,253 @@
...
+import chisel3.internal.sourceinfo.SourceInfo
+
+import scala.annotation.{implicitNotFound, tailrec}
+import scala.collection.mutable
+import scala.collection.immutable.LazyList // Needed for 2.12 alias
+
+package object dataview {
+  case class InvalidViewException(message: String) extends ChiselException(message)
+
+  // TODO should we move the `DataProduct` requirement to `viewAs`
```
Comment (azidar) [inline core/src/main/scala/chisel3/experimental/dataview/package.scala:16]: Why?

File: core/src/main/scala/chisel3/internal/Builder.scala [hunk 13]
```diff
@@ -646,16 +677,37 @@ private[chisel3] object Builder extends LazyLogging {
     }
   }
 
+  // Builds a RenameMap for all Views that do not correspond to a single Data
+  // These Data give a fake ReferenceTarget for .toTarget and .toReferenceTarget that the returned
+  // RenameMap can split into the constituent parts
+  private[chisel3] def makeViewRenameMap: RenameMap = {
```
Comment (azidar) [inline core/src/main/scala/chisel3/internal/Builder.scala:683]: Daaang I didn't realize you did this. Very nice.

File: core/src/main/scala/chisel3/internal/Builder.scala [hunk 14]
```diff
@@ -646,16 +677,37 @@ private[chisel3] object Builder extends LazyLogging {
...
+                 // in tiny designs/testcases that never access anything in chisel3.internal
       checkScalaVersion()
       logger.warn("Elaborating design...")
       val mod = f
       mod.forceName(None, mod.name, globalNamespace)
       errors.checkpoint(logger)
       logger.warn("Done elaborating.")
 
-      (Circuit(components.last.name, components.toSeq, annotations.toSeq), mod)
+      (Circuit(components.last.name, components.toSeq, annotations.toSeq, makeViewRenameMap), mod)
```
Comment (azidar) [inline core/src/main/scala/chisel3/internal/Builder.scala:710]: Now that we are returning a renamemap, perhaps we can fix up our naming stuff so that you can do .toTarget during elaboration, and eliminate ChiselAnnotation?

File: core/src/main/scala/chisel3/internal/SourceInfo.scala [hunk 15]
```diff
@@ -58,4 +58,4 @@ object SourceInfoMacro {
 
 object SourceInfo {
   implicit def materialize: SourceInfo = macro SourceInfoMacro.generate_source_info
-}
+}
```
Comment (azidar) [inline core/src/main/scala/chisel3/internal/SourceInfo.scala:61]: Interesting implementation choice here. Seems a bit counter-intuitive, but I like the brashness if your approach. Perhaps next time, you can consider alternatives? For now though, I'll let this one change slide.

File: docs/src/cookbooks/dataview.md [hunk 16]
```diff
@@ -0,0 +1,179 @@
...
+```scala mdoc:silent:reset
+import chisel3._
+import chisel3.experimental.dataview._
+
+class Foo[T <: Data](val foo: T) extends Bundle
+class Bar[T <: Data](val bar: T) extends Bundle
+
+object Foo {
+  implicit def view[T <: Data]: DataView[Foo[T], Bar[T]] = {
+    DataView(f => new Bar(f.foo.cloneType), _.foo -> _.bar)
```
Comment (azidar) [inline docs/src/cookbooks/dataview.md:35]: gosh darn it, this is why I want `Field`.

File: docs/src/cookbooks/dataview.md [hunk 17]
```diff
@@ -0,0 +1,179 @@
...
+class Bar(val bitwidth: Int) extends Super {
+  val bar = UInt(8.W)
+}
+```
+
+`Foo` and `Bar` cannot be connected directly, but they could be connected by viewing them both as if
+they were instances of their common supertype, `Super`.
+A straightforward approach might run into an issue like the following:
+
+```scala mdoc:fail
```
Comment (azidar) [inline docs/src/cookbooks/dataview.md:151]: Huh, cool. Didn't realize this existed.

File: src/test/scala/chiselTests/stage/ChiselOptionsViewSpec.scala [hunk 18]
```diff
@@ -15,7 +16,7 @@ class ChiselOptionsViewSpec extends AnyFlatSpec with Matchers {
   behavior of ChiselOptionsView.getClass.getName
 
   it should "construct a view from an AnnotationSeq" in {
-    val bar = Circuit("bar", Seq.empty, Seq.empty)
+    val bar = Circuit("bar", Seq.empty, Seq.empty, RenameMap())
```
Comment (azidar) [inline src/test/scala/chiselTests/stage/ChiselOptionsViewSpec.scala:19]: I'm kind of surprised this was the only place you had to update `Circuit`

File: src/main/scala/chisel3/stage/phases/Convert.scala [hunk 19]
```diff
@@ -29,8 +29,7 @@ class Convert extends Phase {
       /* Convert all Chisel Annotations to FIRRTL Annotations */
       a
         .circuit
-        .annotations
-        .map(_.toFirrtl) ++
+        .firrtlAnnotations ++
```
Comment (azidar) [inline src/main/scala/chisel3/stage/phases/Convert.scala:32]: I _thought_ there was another place we needed to change this, but I couldn't find it, so maybe I was wrong?

**Review by azidar — APPROVED** [review]
Very minor changes.

A+, definitely going to be an amazing feature, and you knocked it out of the park with the tests and documentation, as well as the quality of the implementation. Excited to see this in the wild!

File: core/src/main/scala/chisel3/internal/Builder.scala (hunk 14 above)
Comment (azidar) [reply core/src/main/scala/chisel3/internal/Builder.scala:710]: In a future PR, obviously.

File: core/src/main/scala/chisel3/Data.scala (hunk 1 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/Data.scala:554]: This `FIXME` is copy-pasted from the same thing in surrounding lines for BundleLits, VecLits, and DontCare.

We chatted in person but I think the ideal approach is to have aggregate init expressions in FIRRTL itself, or at least add them to Chisel IR and turn them into Wires during ChiselIR => Chirrtl (ie. in the Converter).

This is unrelated to this PR though, but this work would benefit from that.

File: core/src/main/scala/chisel3/Module.scala (hunk 2 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/Module.scala:198]: Important and hard-hitting feedback. I will take this one to heart for future work.

File: core/src/main/scala/chisel3/Module.scala (hunk 3 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/Module.scala:398]: Will push a longer comment.

File: core/src/main/scala/chisel3/RawModule.scala (hunk 7 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/RawModule.scala:289]: 😎

File: core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala (hunk 8 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/experimental/dataview/DataProduct.scala:41]: Yep, and it's one of my favorite things about Scala, everything is an object and most things are a function. If you look at the ScalaDoc (https://www.scala-lang.org/api/2.12.13/scala/collection/Set.html): `Set[A] extends (A) ⇒ Boolean ...`

Similarly, `trait Seq[+A] extends PartialFunction[Int, A] ...` and while I can't find it in the ScalaDoc, `Map[K, +V]` basically extends `PartialFunction[K, V]` but maybe it's via an implicit conversion for variance reasons (`Map` is invariant in the Key type, `PartialFunction` is contravariant for the argument type).

File: core/src/main/scala/chisel3/internal/Builder.scala (hunk 13 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/internal/Builder.scala:683]: Yeah, it worked out a lot better than I expected. This is the sort of thing that weird, custom Stages might run afoul of so it's a thing to mention in release notes, but it's actually a fairly elegant solution in my opinion.

File: core/src/main/scala/chisel3/internal/Builder.scala (hunk 14 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/internal/Builder.scala:710]: While we could do that under your old proposal, I would say we can make `.toTarget` work during elaboration with the following 2 API changes:
1. Require the compiler plugin -- we've already decided we should do this
2. Do not have ports always win in naming over non-ports

(2) is a little iffier but I think that the compiler plugin and the prefixing in particular make this much more palatable. The fear is a `.suggestName` on a port conflicting with the name of something like a `Wire` that's already had `.toTarget` called on it.

File: src/test/scala/chiselTests/stage/ChiselOptionsViewSpec.scala (hunk 18 above)
Comment (jackkoenig) [reply src/test/scala/chiselTests/stage/ChiselOptionsViewSpec.scala:19]: Me too, but yay type-safety!

File: docs/src/cookbooks/dataview.md (hunk 16 above)
Comment (jackkoenig) [reply docs/src/cookbooks/dataview.md:35]: It's not clear if `Field` would actually fix this because `Field` would require that something is an unbound type and this would fail that without the `.cloneType`. I admit I don't have a good solution here but I agree this is a wart.

File: src/main/scala/chisel3/stage/phases/Convert.scala (hunk 19 above)
Comment (jackkoenig) [reply src/main/scala/chisel3/stage/phases/Convert.scala:32]: Yeah I couldn't find it either, if it comes up it's a bug to fix!

File: core/src/main/scala/chisel3/RawModule.scala (hunk 5 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/RawModule.scala:273]: Good question, I think it's just due to the order of implementation and partial refactoring. I'm moving all of `ViewParent` into `ViewParentAPI` and making it just a `class`.

File: core/src/main/scala/chisel3/RawModule.scala (hunk 6 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/RawModule.scala:275]: Note that this is not `overriding` `toAbsoluteTarget`, but rather providing an absolute target for use in `final def toAbsoluteTarget` in `BaseModule`. Explaining in a comment

File: core/src/main/scala/chisel3/experimental/dataview/package.scala (hunk 12 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/experimental/dataview/package.scala:16]: Because then you could call `.viewAs` on anything and it would let you know that you need a `DataProduct` rather than it just saying "method not found". Will play with this and either do that move if it makes sense or delete this comment.

File: core/src/main/scala/chisel3/experimental/dataview/DataView.scala (hunk 11 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/experimental/dataview/DataView.scala:70]: Turns out we can infer it, it's pretty neat. Will include that in my fixes.

File: core/src/main/scala/chisel3/experimental/dataview/package.scala (hunk 12 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/experimental/dataview/package.scala:16]: Given the following code:
```scala
case class Foo(val x: UInt)
class MyModule extends Module {
  val x = Foo(3.U)
  x.viewAs[UInt]
  val in = IO(Input(UInt(8.W)))
  val out = IO(Output(UInt(8.W)))
  out := in
}
```
Without that TODO being done, you get the error:
```
[error] .../Example.scala:8:5: value viewAs is not a member of Foo
[error]   x.viewAs[UInt]
[error]     ^            
```
(which is the same error you get if you forget `import chisel3.experimental.dataview._`)

If I move `DataProduct` to `viewAs` instead of on `DataViewable`, you get:
```
[error] .../File.scala:8:11: Could not find implicit value for DataProduct[Foo].
[error] Please see https://www.chisel-lang.org/chisel3/docs/explanations/dataview#dataproduct
[error]   x.viewAs[UInt]
[error]           ^
```

Comment (jackkoenig) [reply core/src/main/scala/chisel3/experimental/dataview/package.scala:16]: So I went ahead and moved it.

File: core/src/main/scala/chisel3/experimental/dataview/DataView.scala (hunk 11 above)
Comment (jackkoenig) [reply core/src/main/scala/chisel3/experimental/dataview/DataView.scala]: Despite how cool this is, it doesn't work in Scala 2.12 so I'm going to add as a future TODO and revert for now.

It may be possible to provide this only for Scala 2.13 but I'd like to get this merged and figure that out later.

**Comment by aswaterman** [comment]
🎉
